export RC=$(dirname $(dirname $(realpath $(print -P %x))))
source $RC/antigen/antigen.zsh

antigen bundle $RC/zsh
antigen bundle ~/hacking/projects/zsh-zmv

antigen use oh-my-zsh

antigen bundle compleat
antigen bundle common-aliases
antigen bundle colored-man
antigen bundle django
antigen bundle extract
antigen bundle fasd
antigen bundle git
antigen bundle git-extras
antigen bundle github
antigen bundle last-working-dir
antigen bundle pip
antigen bundle pyenv
antigen bundle python
antigen bundle safe-paste
antigen bundle vi-mode
antigen bundle web-search

antigen bundle unixorn/git-extra-commands
antigen bundle peterhurford/git-it-on.zsh
antigen bundle psprint/zsh-navigation-tools
antigen bundle MichaelAquilina/zsh-you-should-use

antigen theme bira

antigen apply
