#!/usr/bin/env python
       
import pygtk; pygtk.require('2.0')
import gtk
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('message', nargs='?', default="Something happened!")
    arguments = parser.parse_args()

    message = gtk.MessageDialog(type=gtk.MESSAGE_INFO, buttons=gtk.BUTTONS_OK)
    message.set_markup("<b>Information</b>")
    message.format_secondary_markup(arguments.message)
    message.run()


