#!/usr/bin/env sh

# Query the connected monitors and decide which ones should be used.  
# Typically, only one monitor is used at a time.  If an external monitor is 
# present, it is preferred over the internal one.

INTERNAL=$(xrandr | grep 'LVDS' | grep "\bconnected\b" | cut -d" " -f1)
EXTERNAL=$(xrandr | grep 'HDMI\|VGA' | grep "\bconnected\b" | cut -d" " -f1)

xrandr --output $EXTERNAL --auto --output $INTERNAL --auto
