#!/usr/bin/env python2

import hashlib 
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('keyword')
parser.add_argument('--root-ports', '-r', action='store_true')
parser.add_argument('--user-ports', '-u', action='store_true')

arguments = parser.parse_args()
root_ports, user_ports = arguments.root_ports, arguments.user_ports

if root_ports and user_ports:
    low_port, high_port = 1, 65535

if root_ports and not user_ports:
    low_port, high_port = 1, 1023

if not root_ports and user_ports:
    low_port, high_port = 1024, 65535

if not root_ports and not user_ports:
    low_port, high_port = 1024, 65535

def clamp (value, minimum, maximum):
    range = maximum - minimum
    return (value % range) + minimum


hash = hashlib.md5(arguments.keyword).hexdigest()
decimal = int(hash, 16)
port = clamp(decimal, low_port, high_port)

print port

