#!/usr/bin/env python2

from __future__ import division

import math
import fileinput

# Read in a distribution.

data = []
        
for line in fileinput.input():
    if line.strip():
        data.append(float(line))

# Calculate its statistical parameters.

mean, std = 0, 0
        
for x in data: mean += x
mean /= len(data)
    
for x in data: std += (x - mean)**2
std = math.sqrt(std / (len(data) - 1))

median = data[len(data) // 2]

# Report the results.

print "mean:  ", mean
print "std:   ", std
print "median:", median
print "min:   ", min(data)
print "max:   ", max(data)
