#!/usr/bin/python

# What It Does
# ============
# Runs the given command in a background process.
#
# Feature Requests
# ================
# 1. Optionally being able to access stdout and/or stderr. 

import os, sys
import subprocess

if os.fork() == 0:
    null = open(os.devnull, 'w')
    try: subprocess.call(sys.argv[1:], stdout=null, stderr=null)
    except OSError: print "Command '{}' not found.".format(sys.argv[1])


