#!/usr/bin/env python3

"""\
Usage:
    hex-to-rgb <hex>...
"""

import sys, re
import docopt

args = docopt.docopt(__doc__)

hex_channel = '[A-Fa-f0-9]{2}'
hex_pattern = re.compile('#?({0})({0})({0})'.format(hex_channel))

for hex_color in args['<hex>']:
    hex_match = hex_pattern.match(hex_color)

    if not hex_match:
        print("'{}' does not appear to be a color.".format(hex_color))
        continue

    rgb = [int(x, 16) for x in hex_match.groups()]
    print('{:3d} {:3d} {:3d}'.format(*rgb))
