#!/usr/bin/env python

import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('columns', nargs='?', type=int, default=80)
arguments = parser.parse_args()

for counter in range(arguments.columns):
    tens, ones = '%02d' % counter
    sys.stdout.write(tens if ones == '0' else ' ')

print

for counter in range(arguments.columns):
    tens, ones = '%02d' % counter
    sys.stdout.write(ones)

print


