#!/usr/bin/env zsh

# This script provides a convenient way to control pianobar remotely.  Pianobar
# provides a FIFO interface capable of accepting remote commands, but it is
# clunky to use on its own.  Zsh completion is also provided for this script.

play=p; pause=p; skip=n; love='+'; hate='-'; upcoming='u'
pipe=~/.config/pianobar/ctl

case $1 in
    (pause)
        echo -n $pause > $pipe ;;
    (play)
        echo -n $play > $pipe ;;
    (skip)
        echo -n $skip > $pipe ;;
    (love)
        echo -n $love > $pipe ;;
    (hate)
        echo -n $hate > $pipe ;;
    (upcoming)
        echo -n $upcoming > $pipe ;;

    (louder)
        amixer -q set Master 5%+ unmute ;;
    (quieter)
        amixer -q set Master 5%- unmute ;;
    (mute)
        amixer -q set Master mute ;;
    (unmute)
        amixer -q set Master unmute ;;

    (*)
        echo "Usage: music play|pause|skip|love|hate|upcoming|louder|quieter|mute|unmute"
        exit 1 ;;
esac
