#!/usr/bin/env python3

import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('rgb', metavar=('red', 'green', 'blue'), nargs=3, type=int)
parser.add_argument('--upper', '-u', action='store_true')
parser.add_argument('--endl', '-e', default='\n')
arguments = parser.parse_args()

for color in arguments.rgb:
    if color > 255:
        print("%d is too large to be a valid RGB value." % color)
        sys.exit(1)
    if color < 0:
        print("%d is too small to be a valid RGB value." % color)
        sys.exit(1)

format = "'#%02x%02x%02x'"
if arguments.upper:
    format = format.upper()

print(format % tuple(arguments.rgb), end=arguments.endl)
