#!/usr/bin/env python3

""" Easily print various numbers of blank lines to the terminal. """

import argparse
from utilities.cursor import terminal_height

parser = argparse.ArgumentParser()
parser.add_argument('lines', default='full', nargs='?')
arguments = parser.parse_args()

lines = 0

if arguments.lines == 'full':
    lines = terminal_height()
elif arguments.lines == 'half':
    lines = terminal_height() // 2
elif arguments.lines == 'third':
    lines = terminal_height() // 3
elif arguments.lines == 'quarter':
    lines = terminal_height() // 4
elif arguments.lines == 'some':
    lines = 5
else:
    try: lines = int(arguments.lines)
    except ValueError:
        print("Unknown number of lines to clear: {}".format(lines))

print('\n' * lines, end='')

